name: ai-utilities
channels:
  - conda-forge
  - r
dependencies:
  - python=3.6.2
  - pip
  - jupyter
  - pytest
  - pytest-cov
  - nb_conda_kernels
  - pylint
  - pandas
  - scikit-learn
  - numpy
  - urllib3
  - cudatoolkit==9.0
  - tensorflow-gpu==1.14.0
  - matplotlib
  - jupyter_contrib_nbextensions
  - ipywidgets
  - ipykernel
  - r-irkernel
  - papermill==2.0.0
  - nbconvert==5.6.1
  - nbformat==5.0.4
  - PyYAML==5.3
  - msrestazure==0.6.2
  - lightgbm==2.3.1
  - Deprecated==1.2.7
  - pip:
    - resnet
    - azure-core
    - azure-common
    - azureml-core==1.0.85
    - azureml-train==1.0.85
    - azureml-contrib-services==1.0.85
    - azureml-contrib-functions==1.0.85
    - pylint-junit
    - pytest-nunit
    - junit-xml
    - python-dotenv
    - Pillow==6.1.0
    - wget==3.2
    - toolz==0.9.0
    - tqdm==4.32.2
    - keras==2.2.4
    - locustio==0.11.0
    - prompt-toolkit==2.0.9
    - PyOpenSSL
    - nb-clean
